# Project: 项目1
# Makefile created by Dev-C++ 5.6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = cir.o 未命名3.o
LINKOBJ  = cir.o 未命名3.o
LIBS     = -L"C:/Users/admini/Documents/Tencent Files/386460761/FileRecv/Dev-Cpp/MinGW64/lib" -L"C:/Users/admini/Documents/Tencent Files/386460761/FileRecv/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Users/admini/Documents/Tencent Files/386460761/FileRecv/Dev-Cpp/MinGW64/include" -I"C:/Users/admini/Documents/Tencent Files/386460761/FileRecv/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/admini/Documents/Tencent Files/386460761/FileRecv/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"C:/Users/admini/Documents/Tencent Files/386460761/FileRecv/Dev-Cpp/MinGW64/include" -I"C:/Users/admini/Documents/Tencent Files/386460761/FileRecv/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/admini/Documents/Tencent Files/386460761/FileRecv/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"C:/Users/admini/Documents/Tencent Files/386460761/FileRecv/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = 项目1.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

cir.o: cir.cpp
	$(CPP) -c cir.cpp -o cir.o $(CXXFLAGS)

未命名3.o: 未命名3.cpp
	$(CPP) -c 未命名3.cpp -o 未命名3.o $(CXXFLAGS)
